# Generated by Django 3.1.7 on 2021-05-05 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_Artist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('art_login_id', models.IntegerField()),
                ('art_fname', models.CharField(max_length=150)),
                ('art_lname', models.CharField(max_length=150)),
                ('art_DOB', models.CharField(max_length=10)),
                ('art_age', models.IntegerField()),
                ('art_gender', models.CharField(max_length=10)),
                ('art_address', models.CharField(max_length=250)),
                ('art_city', models.CharField(max_length=150)),
                ('art_state', models.CharField(max_length=100)),
                ('art_country', models.CharField(max_length=100)),
                ('art_pin', models.CharField(max_length=20)),
                ('art_contact', models.CharField(max_length=20)),
                ('art_email', models.CharField(max_length=250)),
                ('art_work_title', models.CharField(max_length=250)),
                ('art_compensation', models.CharField(max_length=50)),
                ('art_bio', models.CharField(max_length=300)),
                ('art_headphoto', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='tbl_CastingApplication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appl_castingcall_id', models.IntegerField()),
                ('appl_art_id', models.IntegerField()),
                ('video_yes_no', models.CharField(max_length=350)),
                ('application_status', models.IntegerField()),
                ('application_result', models.CharField(max_length=20)),
                ('dt', models.CharField(max_length=10)),
                ('tm', models.CharField(max_length=10)),
                ('result', models.CharField(max_length=350)),
            ],
        ),
        migrations.CreateModel(
            name='tbl_CastingCall',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('castingteam_id', models.IntegerField()),
                ('posted_date', models.CharField(max_length=50)),
                ('posted_time', models.CharField(max_length=50)),
                ('character', models.CharField(max_length=150)),
                ('role_desc', models.CharField(max_length=500)),
                ('gender', models.CharField(max_length=50)),
                ('age_from', models.IntegerField()),
                ('age_to', models.IntegerField()),
                ('castingteam_prod_categid', models.IntegerField()),
                ('call_expiry', models.CharField(max_length=50)),
                ('job_duration', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='tbl_CastingTeam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('castingteam_login_id', models.IntegerField()),
                ('castingteam_company', models.CharField(max_length=250)),
                ('castingteam_producer', models.CharField(max_length=150)),
                ('castingteam_address', models.CharField(max_length=250)),
                ('castingteam_city', models.CharField(max_length=150)),
                ('castingteam_state', models.CharField(max_length=150)),
                ('castingteam_country', models.CharField(max_length=150)),
                ('castingteam_pincode', models.CharField(max_length=50)),
                ('castingteam_contact', models.CharField(max_length=20)),
                ('castingteam_email', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='tbl_CastingTeamProductions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('castingteam_id', models.IntegerField()),
                ('castingteam_prod_categid', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='tbl_Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=15)),
                ('contact', models.CharField(max_length=20)),
                ('msg', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='tbl_Login',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uname', models.CharField(max_length=50)),
                ('pswd', models.CharField(max_length=20)),
                ('utype', models.CharField(max_length=20)),
                ('status', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='tbl_Plot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plot_castingcall_id', models.IntegerField()),
                ('plot_desc', models.CharField(max_length=500)),
                ('plot_emotion', models.CharField(max_length=20)),
                ('plot_video_duration', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='tbl_ProductionMaster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prod_categ', models.CharField(max_length=150)),
                ('emotion_capture', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='tbl_VideoUpload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_id', models.IntegerField()),
                ('video_file', models.CharField(max_length=500)),
            ],
        ),
    ]
